import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowRight, Download, Check, Plus, Menu, X, CalendarDays, MessageSquare, FileSpreadsheet, Users, WalletCards, ClipboardList} from 'lucide-react';
import './styles.css';
const apk='https://github.com/mudrikazq24/bukucateringindonesia/releases/download/v.1.0.1/BukuCatering-v1.0.1.apk';
const screens=[['beranda','Beranda','Tahu apa yang perlu disiapkan hari ini.','Lihat ringkasan pengiriman dan menu sebelum mulai menyiapkan pesanan.'],['jadwal','Jadwal','Setiap pengiriman punya waktunya.','Pantau pengiriman berdasarkan tanggal dan slot. Lebih mudah menyusun persiapan dapur.'],['pesanan','Pesanan','Pesanan pelanggan, dalam satu catatan.','Cari nama atau nomor pesanan, gunakan filter pembayaran, lalu buka rincian pesanan pelanggan.'],['detail-pesanan','Detail pesanan','Rincian pesanan, sampai sisa tagihannya.','Lihat total pesanan, pembayaran diterima, sisa tagihan, dan jadwal pengiriman.'],['pengaturan','Pengaturan','Data usaha, di tempat yang mudah ditemukan.','Kelola profil usaha, zona waktu, rekening, QRIS, pelanggan, dan master paket menu.']];
const faqs=[['Apakah tersedia trial?','Ya, tersedia trial 14 hari untuk mencoba BukuCatering. Akun dibuatkan oleh admin. Setelah trial, tersedia pilihan langganan 1 bulan atau 1 tahun.'],['Bagaimana cara mendapat akun?','Akun dibuatkan oleh admin BukuCatering. Aplikasi tidak menyediakan pendaftaran mandiri. Setelah mendapatkan akun dan langganan aktif, kamu bisa mulai mencatat pesanan.'],['Bagaimana sistem langganannya?','Pilihan masa langganan adalah 1 bulan atau 1 tahun. Aktivasi dan perpanjangan dikonfirmasi oleh admin. Saat masa aktif berakhir, ekspor, pengaturan, dan logout tetap tersedia.'],['Apakah pesanan WhatsApp masuk otomatis?','Pesanan dari WhatsApp atau percakapan langsung dicatat manual. Invoice berupa teks dapat disalin atau dibagikan melalui Android untuk diteruskan ke pelanggan.'],['Apakah pembayaran terkonfirmasi otomatis?','Pemilik usaha memeriksa pembayaran, lalu mencatat satu DP dan pelunasan, atau langsung lunas. Rekening dapat dicantumkan pada invoice; gambar QRIS dibagikan terpisah.'],['Bagaimana cara memasang aplikasi?','Unduh APK, buka file di Android, lalu izinkan instalasi dari browser jika diminta. Masuk dengan akun dari admin. Saat ini distribusi menggunakan APK langsung.']];
const capabilities=[
 [CalendarDays,'Tanggal yang kamu pilih,','jadwal yang tercatat.','Satu pesanan bisa punya beberapa tanggal dan slot: sarapan, makan siang, atau makan malam. Menu dan jumlahnya dapat berbeda.'],
 [WalletCards,'Sudah kirim dan sudah bayar,','dua hal yang berbeda.','Catat pengiriman per tanggal-slot. Pantau DP, pelunasan, dan sisa tagihan pada pesanan secara terpisah.'],
 [ClipboardList,'Sebelum mulai masak,','lihat kebutuhan menu.','Beranda dan jadwal membantu melihat pengiriman serta rekap menu yang perlu disiapkan.'],
 [MessageSquare,'Invoice teks,','siap dibagikan.','Tinjau rincian pesanan, lalu salin atau bagikan teks untuk diteruskan lewat WhatsApp. QRIS dibagikan sebagai gambar terpisah.'],
 [FileSpreadsheet,'Butuh rekap?','Bawa ke Excel.','Ekspor pengiriman berdasarkan satu tanggal atau rentang tanggal. Simpan atau bagikan file dari Android.'],
 [Users,'Pelanggan dan menu,','siap dipakai kembali.','Kelola data pelanggan dan master menu dari pengaturan. Pilih menu yang tersimpan atau tulis menu langsung saat mencatat pesanan.']
];
function useReveal(){useEffect(()=>{if(!('IntersectionObserver' in window)||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const nodes=document.querySelectorAll('[data-reveal]');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:0.08});nodes.forEach(node=>{if(node.getBoundingClientRect().top>=window.innerHeight){node.classList.add('reveal-ready');observer.observe(node)}});return()=>{observer.disconnect();nodes.forEach(node=>node.classList.remove('reveal-ready'))}},[])}
function ScheduleDemo(){const [selected,setSelected]=useState([21,23]);const days=[['Sen',21],['Sel',22],['Rab',23],['Kam',24],['Jum',25]];return <div className="scheduleDemo" data-reveal><div className="demoTop"><CalendarDays size={18}/><span>CONTOH PESANAN MULTI-TANGGAL</span><span className="sampleBadge">Demo</span></div><h3>Senin dan Rabu saja?<br/><em>Catat dua tanggal itu saja.</em></h3><p>Pilih tanggal pada contoh ini. Hari di antaranya tidak ikut ditambahkan.</p><div className="demoDays" role="group" aria-label="Pilih tanggal contoh September 2026">{days.map(([d,n])=><button key={n} aria-label={`${d}, ${n} September 2026`} aria-pressed={selected.includes(n)} onClick={()=>setSelected(prev=>prev.includes(n)?prev.filter(x=>x!==n):[...prev,n].sort((a,b)=>a-b))}><span>{d}</span><b>{n}</b><span className="dayMark">{selected.includes(n)?<Check size={14}/>:<span>—</span>}</span></button>)}</div><div className="demoResult" aria-live="polite" aria-atomic="true"><span>JADWAL TERCATAT</span><p>{selected.length?selected.map(n=>`${days.find(x=>x[1]===n)[0]}, ${n} Sep`).join(' · '):'Belum ada tanggal dipilih'}</p></div><small>Ilustrasi September 2026 · Pilihan ini tidak menyimpan pesanan.</small></div>}
function App(){useReveal();const tabsRef=useRef(null);const [active,setActive]=useState(0);function tabKey(event,index){let next=index;if(event.key==='ArrowRight')next=(index+1)%screens.length;else if(event.key==='ArrowLeft')next=(index+screens.length-1)%screens.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=screens.length-1;else return;event.preventDefault();setActive(next);tabsRef.current?.querySelectorAll('[role=tab]')[next]?.focus();}const [menu,setMenu]=useState(false);const s=screens[active];return <>
<header className="header"><a className="brand" href="#top" aria-label="BukuCatering beranda"><img src="/bukucatering-icon.svg" alt=""/>BukuCatering<span className="brandDot">.</span></a><button className="menuToggle" aria-label={menu?'Tutup navigasi':'Buka navigasi'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}>{[['#fitur','Fitur'],['#tampilan','Lihat aplikasi'],['#mulai','Cara mulai']].map(([h,t])=><a key={h} href={h} onClick={()=>setMenu(false)}>{t}</a>)}</nav><a href={apk} className="navDownload">Unduh aplikasi <ArrowUpRight size={17}/></a></header>
<main id="top"><section className="hero wrap"><div className="heroCopy"><div className="eyebrow"><span/> CATAT PESANAN. INGAT TANGGAL KIRIM.</div><h1>Dapur tertata,<br/><span>hati lebih lega.</span></h1><p>Catat pesanan sesuai tanggal kirimnya. Lihat menu yang perlu disiapkan, pantau pembayaran, lalu bagikan invoice ke pelanggan.</p><a className="button" href={apk}><Download size={18}/> Unduh untuk Android <ArrowUpRight size={19}/></a><div className="downloadMeta">Trial 14 hari <span>·</span> Android <span>·</span> Akun dari admin</div><a className="heroNote" href="#alur"><span className="noteLine"/> Lihat cara tanggal kirim dicatat <ArrowRight size={16}/></a></div><div className="heroArt"><div className="artLabel"><span>CATATAN DAPUR</span><span>01 / BERANDA</span></div><div className="phone"><img src="/screenshots/beranda.jpg" alt="Beranda terbaru BukuCatering dengan ringkasan usaha, persiapan dapur, dan jadwal hari ini"/></div><div className="paperNote"><span className="pin"/><small>SEBELUM DAPUR SIBUK</small><p>Tanggal jelas.<br/>Menu siap.<br/>Catatan rapi.</p><span className="noteSignature">Semua mulai dari catatan.</span></div></div></section>
<div className="topicStrip"><div className="wrap"><span>Satu buku untuk<br/><b>urusan dapurmu.</b></span><span>01 <b>Pesanan</b></span><span>02 <b>Jadwal kirim</b></span><span>03 <b>Pembayaran</b></span><span>04 <b>Pelanggan</b></span></div></div>
<section className="workflow wrap" id="alur"><div className="sectionIntro" data-reveal><span className="eyebrow">01 — TANGGALNYA JANGAN TERTUKAR</span><h2>Pesan hari ini.<br/>Kirim di hari<br/><em>yang dipilih.</em></h2><p>Pesanan beberapa hari tidak harus berurutan. Setiap tanggal punya menu, jumlah, slot makan, dan status kirimnya sendiri.</p><div className="workflowFoot"><Check size={17}/><span>Satu pesanan. Beberapa jadwal yang jelas.</span></div></div><ScheduleDemo/></section>
<section className="features wrap" id="fitur"><div className="featureHeading" data-reveal><div><span className="eyebrow">02 — URUSAN HARIAN, LEBIH TERTATA</span><h2>Dari catatan pesanan<br/>sampai rekap usaha.</h2></div><p>Dirancang untuk pemilik catering<br/>yang mencatat pesanan sehari-hari.</p></div><div className="capabilityGrid">{capabilities.map(([Icon,t,u,d],i)=><article data-reveal key={t}><div className="capabilityTop"><Icon size={22}/><span>0{i+1}</span></div><h3>{t}<br/>{u}</h3><p>{d}</p></article>)}</div></section>
<section className="showcase" id="tampilan"><div className="wrap"><div className="showcaseHeading" data-reveal><div><span className="eyebrow">03 — INTIP BUKUNYA</span><h2>Akrab dari<br/>pertama dibuka.</h2></div><p>Lihat tampilan asli BukuCatering.<br/>Pilih halaman yang ingin kamu kenali.</p></div><div className="appPreview" data-reveal><div className="previewCopy"><div className="tabs" ref={tabsRef} role="tablist" aria-label="Halaman aplikasi">{screens.map((x,i)=><button role="tab" tabIndex={active===i?0:-1} onKeyDown={e=>tabKey(e,i)} id={`tab-${i}`} aria-controls="screen-panel" aria-selected={active===i} key={x[0]} onClick={()=>setActive(i)}>{x[1]}</button>)}</div><div key={s[0]} className="screenPanel" tabIndex={0} id="screen-panel" role="tabpanel" aria-labelledby={`tab-${active}`}><span className="previewNumber">0{active+1} / 0{screens.length}</span><h3>{s[2]}</h3><p>{s[3]}</p><a className="textLink" href={apk}>Coba di Android <ArrowRight size={18}/></a></div><small className="previewCaption">SCREENSHOT APLIKASI TERBARU</small></div><div className="previewImage"><img key={s[0]} src={`/screenshots/${s[0]}.jpg`} alt={`Tampilan ${s[1]} BukuCatering`} loading="lazy"/><span>{s[1]} / BukuCatering</span></div></div></div></section>
<section className="gettingStarted wrap" id="mulai"><div className="sectionIntro" data-reveal><span className="eyebrow">04 — MULAI DARI SINI</span><h2>Siapkan Android.<br/>Buka buku baru.</h2><p>Coba BukuCatering dengan trial 14 hari. Akun dibuatkan oleh admin; setelah trial, tersedia pilihan langganan 1 bulan atau 1 tahun.</p></div><ol>{[['Unduh aplikasinya','Ambil file APK v1.0.0 lewat tombol unduh di halaman ini.'],['Pasang di Android','Buka file APK. Izinkan instalasi dari browser jika perangkat memintanya.'],['Masuk, lalu mulai catat','Gunakan akun dari admin dengan langganan aktif untuk mengelola usaha.']].map(([t,d],i)=><li data-reveal key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></section>
<section className="faq wrap" id="faq"><div data-reveal><span className="eyebrow">SEBELUM MULAI</span><h2>Ada yang<br/>ingin ditanyakan?</h2></div><div>{faqs.map(([q,a])=><details data-reveal key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></section>
<section className="closing"><div className="wrap" data-reveal><span className="eyebrow">BUKUCATERING UNTUK ANDROID</span><div><h2>Besok ada pesanan lagi.<br/><i>Hari ini, mulai rapikan.</i></h2><a className="button" href={apk}>Unduh BukuCatering <Download size={19}/></a></div><p>Trial 14 hari · Versi 1.0.0 · APK ±26 MB · Akun dari admin</p></div></section></main>
<footer className="wrap"><a className="brand" href="#top"><img src="/bukucatering-icon.svg" alt=""/>BukuCatering<span className="brandDot">.</span></a><p>Dapur tertata, hati lebih lega.</p><small>© 2026 BukuCatering</small></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
