import React from 'react';
import {createRoot} from 'react-dom/client';
import {CalendarDays, ClipboardList, WalletCards, Users, Download, Smartphone, CheckCircle2, ChevronDown, ArrowRight, ShieldCheck} from 'lucide-react';
import './styles.css';
const apk='https://github.com/mudrikazq24/bukucatering_landing/releases/download/v1.0.0/BukuCatering-v1.0.0.apk';
const features=[
 [ClipboardList,'Pesanan lebih rapi','Cari dan pantau pesanan pelanggan, status pembayaran, serta status pengiriman dalam satu tempat.'],
 [CalendarDays,'Jadwal terkontrol','Lihat jadwal pengiriman berdasarkan tanggal dan slot agar persiapan dapur lebih terarah.'],
 [WalletCards,'Pembayaran tercatat','Pantau total pesanan, pembayaran yang diterima, dan sisa tagihan dengan jelas.'],
 [Users,'Data usaha terpusat','Kelola pelanggan, rekening, QRIS, profil usaha, zona waktu, dan master menu dari aplikasi.']
];
const shots=[['/screenshots/beranda.jpg','Beranda','Ringkasan pengiriman dan menu yang perlu disiapkan.'],['/screenshots/jadwal.jpg','Jadwal','Pantau jadwal berdasarkan tanggal dan slot pengiriman.'],['/screenshots/pesanan.jpg','Pesanan','Cari, filter, dan lihat status pesanan dengan cepat.'],['/screenshots/detail-pesanan.jpg','Detail pesanan','Lihat rincian pembayaran dan jadwal pengiriman.']];
const faqs=[['Apakah ada trial gratis?','Ya. Pengguna baru dapat mencoba BukuCatering gratis selama 7 hari. Setelah masa trial berakhir, pilih paket langganan untuk melanjutkan penggunaan.'],['Apakah BukuCatering tersedia di Play Store?','Saat ini BukuCatering didistribusikan langsung melalui website resmi. Versi Play Store dapat tersedia pada tahap berikutnya.'],['Bagaimana cara memasang APK?','Tekan Download untuk Android, buka file APK yang sudah diunduh, lalu izinkan instalasi dari browser jika Android memintanya.'],['Apakah perlu mengunduh ulang saat ada versi baru?','Selama distribusi masih menggunakan APK langsung, versi terbaru perlu diunduh dan dipasang kembali.'],['Untuk siapa BukuCatering dibuat?','BukuCatering ditujukan untuk pemilik usaha catering dan usaha makanan berbasis pesanan yang ingin mengelola operasional dengan lebih rapi.']];
function App(){return <>
<header className="nav"><a className="brand" href="#top"><img src="/bukucatering-icon.svg"/><b>BukuCatering</b></a><nav><a href="#fitur">Fitur</a><a href="#preview">Tampilan</a><a href="#cara">Cara mulai</a><a href="#faq">FAQ</a></nav><a className="btn small" href={apk}><Download size={17}/> Download</a></header>
<main id="top">
<section className="hero"><div className="heroCopy"><div className="eyebrow"><Smartphone size={16}/> Aplikasi Android untuk usaha catering</div><h1>Dapur tertata,<br/><em>hati lebih lega.</em></h1><p>Kelola pesanan, jadwal pengiriman, pembayaran, dan pelanggan dalam satu aplikasi yang sederhana untuk operasional catering sehari-hari.</p><div className="actions"><a className="btn" href={apk}><Download size={20}/> Download untuk Android</a><a className="ghost" href="#preview">Lihat aplikasinya <ArrowRight size={18}/></a></div><div className="meta"><CheckCircle2 size={17}/> Trial gratis 7 hari <span>•</span> Versi 1.0.0 <span>•</span> Android <span>•</span> ±26 MB</div></div>
<div className="heroVisual"><div className="softBlob"></div><div className="phoneShot"><img src="/screenshots/beranda.jpg" alt="Beranda BukuCatering"/></div><div className="floatCard"><span>Pengiriman hari ini</span><strong>Lebih mudah dipantau</strong></div></div></section>
<section className="trust"><ShieldCheck size={18}/><span>Dirancang untuk membantu operasional usaha catering sehari-hari.</span></section>
<section className="section" id="fitur"><div className="sectionHead"><span>FITUR UTAMA</span><h2>Semua yang penting, dalam satu alur.</h2><p>Informasi pesanan dibuat jelas agar kamu bisa fokus pada persiapan dan pengiriman.</p></div><div className="grid">{features.map(([I,t,d])=><article key={t}><div className="icon"><I/></div><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="showcase" id="preview"><div className="sectionHead"><span>TAMPILAN APLIKASI</span><h2>Sederhana, hangat, dan mudah dibaca.</h2><p>Tampilan BukuCatering menggunakan informasi yang jelas, kartu yang rapi, dan status yang mudah dikenali.</p></div><div className="shots">{shots.map(([src,t,d],i)=><article className={i===0?'shot featured':'shot'} key={t}><div className="shotImg"><img src={src} alt={`${t} BukuCatering`}/></div><div className="shotCopy"><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
<section className="steps" id="cara"><div><span className="label">MULAI SEKARANG</span><h2>Empat langkah untuk mulai memakai BukuCatering.</h2><p>Download aplikasi, mulai trial gratis 7 hari, lalu lanjutkan berlangganan jika BukuCatering sesuai untuk usahamu.</p></div><div className="stepList">{[['01','Download APK','Unduh BukuCatering v1.0.0 melalui tombol resmi di website.'],['02','Install di Android','Buka APK dan izinkan instalasi dari browser jika diminta perangkat.'],['03','Coba gratis 7 hari','Aktifkan akun dan gunakan BukuCatering gratis selama masa trial 7 hari.'],['04','Lanjutkan berlangganan','Setelah trial berakhir, pilih paket langganan untuk terus menggunakan BukuCatering.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}</div></section>
<section className="download"><img src="/bukucatering-icon.svg"/><div><span>BUKUCATERING v1.0.0</span><h2>Siap membuat operasional catering lebih tertata?</h2><p>Download BukuCatering untuk Android dan coba gratis selama 7 hari.</p></div><a className="btn light" href={apk}><Download size={20}/> Download APK</a></section>
<section className="section faq" id="faq"><div className="sectionHead"><span>FAQ</span><h2>Pertanyaan yang sering ditanyakan</h2></div><div className="faqList">{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></section>
</main><footer><div className="brand"><img src="/bukucatering-icon.svg"/><b>BukuCatering</b></div><p>Dapur tertata, hati lebih lega.</p><small>© 2026 BukuCatering · Versi Android 1.0.0</small></footer>
</>}
createRoot(document.getElementById('root')).render(<App/>);
